"""add default to booking

Revision ID: ef1a085c3e59
Revises: 6c0423ecd722
Create Date: 2026-06-15 23:27:34.555995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1a085c3e59'
down_revision: Union[str, Sequence[str], None] = '6c0423ecd722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELLED_BY_USER', 'CANCELLED_BY_ADMIN', 'NOT_VISITED', name='status'), server_default='BOOKED', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_active_booking_per_slot', 'bookings', ['slot_id'], unique=True, postgresql_where=sa.text("status = 'BOOKED'"), sqlite_where=sa.text("status = 'BOOKED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_active_booking_per_slot', table_name='bookings', postgresql_where=sa.text("status = 'BOOKED'"), sqlite_where=sa.text("status = 'BOOKED'"))
    op.drop_table('bookings')
    # ### end Alembic commands ###
