"""add fields "phone" and "password_hash" to users model

Revision ID: b4d12914c925
Revises: f980b669d85e
Create Date: 2026-06-12 14:16:23.364486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4d12914c925"
down_revision: Union[str, Sequence[str], None] = "f980b669d85e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=False)
    )
    op.add_column("users", sa.Column("password_hash", sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
